module WorkersData
  DATA = [
    { name: "吉久保", group: 0 },
    { name: "椛沢", group: 0 },
    { name: "片根", group: 0 },
    { name: "平山", group: 0 },
    { name: "小沢", group: 0 },
    { name: "加藤", group: 0 },
    { name: "笹沼", group: 0 },
    { name: "小川", group: 0 },
    { name: "宮下", group: 0 },
    { name: "小沢", group: 0 },
    { name: "大越", group: 0 },
    { name: "山品", group: 0 },
    { name: "徳永", group: 0 },
    { name: "岡田", group: 0 },
    { name: "金田", group: 1 },
    { name: "樫村", group: 1 },
    { name: "杉本", group: 1 },
    { name: "直井", group: 1 },
    { name: "小野崎", group: 1 },
    { name: "芳賀", group: 1 },
    { name: "山口", group: 1 },
    { name: "三浦(JSC)", group: 1 },
    { name: "佐川", group: 1 },
    { name: "中島", group: 1 },
    { name: "山形", group: 2 },
    { name: "菊池", group: 2 },
    { name: "鈴木（山形）", group: 2 },
    { name: "稲田", group: 3 },
    { name: "渡辺", group: 3 },
    { name: "木内", group: 3 },
    { name: "田崎", group: 3 },
    { name: "渋谷", group: 3 },
    { name: "渡邉", group: 3 },
    { name: "佐渡", group: 3 },
    { name: "村上", group: 3 },
    { name: "諏訪", group: 3 },
    { name: "根本", group: 3 },
    { name: "三浦(聖和)", group: 3 },
    { name: "鈴木(聖和)", group: 3 },
    { name: "大友", group: 4 },
    { name: "椎名", group: 4 },
    { name: "宇佐美", group: 4 },
  ].freeze
end
