Worker.find_or_create_by!(name: "吉久保", group:0)
Worker.find_or_create_by!(name: "椛沢", group:0)
Worker.find_or_create_by!(name: "片根", group:0)
Worker.find_or_create_by!(name: "平山", group:0)
Worker.find_or_create_by!(name: "小沢", group:0)
Worker.find_or_create_by!(name: "加藤", group:0)
Worker.find_or_create_by!(name: "笹沼", group:0)
Worker.find_or_create_by!(name: "小川", group:0)
Worker.find_or_create_by!(name: "近藤", group:0)
Worker.find_or_create_by!(name: "宮下", group:0)
Worker.find_or_create_by!(name: "大越", group:0)
Worker.find_or_create_by!(name: "山品", group:0)
Worker.find_or_create_by!(name: "徳永", group:0)
Worker.find_or_create_by!(name: "岡田", group:0)
Worker.find_or_create_by!(name: "金田", group:1)
Worker.find_or_create_by!(name: "樫村", group:1)
Worker.find_or_create_by!(name: "杉本", group:1)
Worker.find_or_create_by!(name: "直井", group:1)
Worker.find_or_create_by!(name: "小野崎", group:1)
Worker.find_or_create_by!(name: "芳賀", group:1)
Worker.find_or_create_by!(name: "山口", group:1)
Worker.find_or_create_by!(name: "三浦(JSC)", group:1)
Worker.find_or_create_by!(name: "佐川", group:1)
Worker.find_or_create_by!(name: "中島", group:1)
Worker.find_or_create_by!(name: "山形", group:2)
Worker.find_or_create_by!(name: "菊池", group:2)
Worker.find_or_create_by!(name: "鈴木（山形）", group:2)
Worker.find_or_create_by!(name: "稲田", group:3)
Worker.find_or_create_by!(name: "渡辺", group:3)
Worker.find_or_create_by!(name: "木内", group:3)
Worker.find_or_create_by!(name: "田崎", group:3)
Worker.find_or_create_by!(name: "渋谷", group:3)
Worker.find_or_create_by!(name: "渡邉", group:3)
Worker.find_or_create_by!(name: "佐渡", group:3)
Worker.find_or_create_by!(name: "村上", group:3)
Worker.find_or_create_by!(name: "諏訪", group:3)
Worker.find_or_create_by!(name: "根本", group:3)
Worker.find_or_create_by!(name: "三浦(聖和)", group:3)
Worker.find_or_create_by!(name: "鈴木(聖和)", group:3)
Worker.find_or_create_by!(name: "大友", group:4)
Worker.find_or_create_by!(name: "椎名", group:4)
Worker.find_or_create_by!(name: "宇佐美", group:4)
Worker.find_or_create_by!(name: "入力", group:5)

Vehicle.find_or_create_by!(number:"...8", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"88-78", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"81-18", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"80-08", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"23-47", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"86-78", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"50-00", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"51-51", vehicle_type: 0)
Vehicle.find_or_create_by!(number:"80-73", vehicle_type: 1)
Vehicle.find_or_create_by!(number:"47-56", vehicle_type: 1)
Vehicle.find_or_create_by!(number:"85-58", vehicle_type: 1)
Vehicle.find_or_create_by!(number:"30-96", vehicle_type: 1)
Vehicle.find_or_create_by!(number:"85-68", vehicle_type: 1)
Vehicle.find_or_create_by!(number:"88-23", vehicle_type: 1)
Vehicle.find_or_create_by!(number:"37-98", vehicle_type: 2)
Vehicle.find_or_create_by!(number:"81-88", vehicle_type: 2)
Vehicle.find_or_create_by!(number:"29-58", vehicle_type: 3)
Vehicle.find_or_create_by!(number:"88-52", vehicle_type:4)
Vehicle.find_or_create_by!(number:"32-62", vehicle_type:5)
Vehicle.find_or_create_by!(number:"52-10", vehicle_type:5)
Vehicle.find_or_create_by!(number:"60-39", vehicle_type:5)
Vehicle.find_or_create_by!(number:"80-00", vehicle_type:5)
Vehicle.find_or_create_by!(number:"42-37", vehicle_type:5)
Vehicle.find_or_create_by!(number:"85-10", vehicle_type:5)
Vehicle.find_or_create_by!(number:"99", vehicle_type:5)
